import type { Metadata } from "next";
import "./globals.css";
import useTextDirection from "@/hooks/use-text-direction";

// TODO update meta data later
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{
    children: React.ReactNode;
}>;

export default function RootLayout({ children }: RootLayoutProps) {
    const { dir, locale } = useTextDirection();

    return (
        <html lang={locale} dir={dir}>
            <body className="w-full overflow-x-hidden">{children}</body>
        </html>
    );
}
